title: "Ensemble Géométrique"
author: "Project Ensemble Géométrique"
description: "Website for Project Ensemble Géométrique"
permalink: /:title/
lang: "ja"
excerpt_separator: "\n\n\n"
date_format: "%Y-%m-%d"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:ensemble.geometrique.1001@gmail.com"}
  - {title: GitHub, icon: github, url: "https://github.com/Ensemble-Geometrique"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
